#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTGYRO,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FourBar,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Initialize.h"
#include "../common/MotionLibrary.h"
#include "../common/RotationLibrary.h"
#include "../common/ArmLibrary.h"
#include "JoystickDriver.c"
task MoveArmUp()
{
		MoveArm(-6.5, 80);
}

task main()
{
	Initialize();
	Move(80, 1.5);
	TurnDegree(-90, -20, 20);
	Move(80, 1.5);

	//MoveVCupToPosition(100);
  //Initialize();
	//StartTask(MoveArmUp);
	//MoveVCupToPosition(50);
	//Move(80, 1.7);
	//TurnDegree(40, 20, -20);
	//Move(80, 2.9);
	//sleep(100);
	//MoveVCupToPosition(1);
	//MoveArm(2, 50);
	//Move(-80, 3);
	//MoveArm(4.5, 50);
	//MoveVCupToPosition(50);


}
