#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S3,     HTGYRO,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     FourBar,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Initialize.h"
#include "../CommonLibraries/MotionLibrary.h"
#include "../CommonLibraries/RotationLibrary.h"
#include "../CommonLibraries/ArmLibrary.h"
#include "JoystickDriver.c"
task MoveArmUp()
{
		MoveArm(-6.5, 80);
}

task main()
{
 // Initialize();
	//StartTask(MoveArmUp);
	//MoveVCupToPosition(50);
	//Move(80, 1.7);
	//TurnDegree(40, 20, -20);
	//Move(80, 2.9);
	//sleep(100);
	//MoveVCupToPosition(1);
	//MoveArm(2, 50);
	//Move(-80, 3);
	//MoveArm(4.5, 50);
	//MoveVCupToPosition(50);

	MoveArm(1, 50);
}
