#pragma config(Sensor, S1,     HTMAG,               sensorAnalogInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: hitechnic-magfield-test1.c 112 2012-10-04 17:44:38Z xander $
 */

/**
 * hitechnic-magfield.h provides an API for the HiTechnic Magnetic Field Sensor.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 *
 * Credits:
 * - Big thanks to HiTechnic for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.51 AND HIGHER.
 * Xander Soldaat (xander_at_botbench.com)
 * 27 July 2010
 * version 0.1
 */

#include "drivers/hitechnic-magfield.h"

task main ()
{
		HTMAGstartCal(HTMAG);
    nxtDisplayTextLine(2, "Bias: %4d", calibrationValue);
    PlaySound(soundBlip);

    while(nNxtButtonPressed != kEnterButton)
    {
      calibrationValue = HTMAGreadCal(HTMAG);
      magFieldValue = HTMAGreadVal(HTMAG);
      nxtDisplayTextLine(2, "Bias: %4d", calibrationValue);
    }
  }

/*
 * $Id: hitechnic-magfield-test1.c 112 2012-10-04 17:44:38Z xander $
 */
