#pragma config(Sensor, S1,     Accelerometer,  sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Libraries/Write.h"
task main()
{
	int Times = 0;
	InitializeWrite();
	WriteLine(0, "Made by Isaac!");
	WriteLine(1, "Idea by AJ!");
	WriteLine(7, "Bye...");
	while(true)
	{
		Sleep(1000);
		WriteDebugInt(Times);
		Times++;
	}
}
