#pragma config(Sensor, S1,     LineFollower,   sensorLightActive)
#pragma config(Sensor, S2,     Color,          sensorCOLORFULL)
#pragma config(Motor,  motorA,          LeftDrive,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          RightDrive,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int setpoint = 40;
int power = 14;
int lightreading = 0;
int leftpower = 0;
int rightpower = 0;
int error = 0;
int colorReading = 0;
int delayTime = 0;

int max(int a, int b)
{
  if(a > b) return a;
  else return b;
}

task main()
{
  while(true)
  {
    colorReading = SensorValue[Color];
    nxtDisplayString(4, "%i", colorReading);

  	if(SensorValue[Color] !=2)
    {
  	lightreading = SensorValue[LineFollower];
  	nxtDisplayString(3, "%i", lightreading);
    error = setpoint - lightreading;
    leftpower = max(0, power + error);
    rightpower = max(0, power - error);
    motor[LeftDrive] = leftpower;
    motor[RightDrive] = rightpower;
  	}
  	else
  	{
  		motor[LeftDrive] = 100;
  		motor[RightDrive] = -10;
  		wait1Msec(1350);
  		motor[motorA] = 0;
  		motor[motorB] = 0;
  		delayTime = rand()%2000 + 1000;
  		wait1Msec(delayTime);
  		nxtDisplayString(7, "%i", delayTime);
  	}
  }
}
